### ISSUE TITLE
오노테이션(@GetMapping) 아래 공백 삭제해서 메소드와 붙여주세요.

### ISSUE THREAD

**Issue by sigmadream** [pt807/ks-web#1]
https://github.com/pt807/ks-web/blob/30810ff5ce57d68b0aa48a37042c204fc6b5b44a/src/main/java/com/daejun/app/IndexController.java#L9

**Comment by pt807** [comment]
수정했습니다.

**Comment by sigmadream** [comment]
수고하셨습니다

2020년 4월 11일 (토) 오후 5:05, pt807 <notifications@github.com>님이 작성:
